export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const FIND_PRODUCTS = 'FIND_PRODUCTS';
export const PAGINATION = 'PAGINATION';
export const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';